version: '3'
services:
  xtion_camera_humble:
    build: .
    container_name: xtion_ros2
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix 
      - ./openni2_interfaces/:/colcon_ws/src/openni2_interfaces/
      - ./openni2_service/:/colcon_ws/src/openni2_service/
    privileged: true
    #network_mode: host
    network_mode: bridge #important for network setting
    ipc: host
    #pid: host

    command: ros2 launch openni2_service openni2_image_service.launch.py

